project:
  title: "{{< var site_title >}}"
  type: website
  output-dir: docs

website:
  title: "DS 5100 Activities"
  repo-actions: [edit]
  repo-url: "https://github.com/ontoligent/DS5100-activities" # Variable does not work here
  sidebar:
    style: "docked"
    search: true
    page-navigation: true
    contents:
        - section: "M01"
          contents:
            - "activities/M01-01-Using-Rivanna.qmd"
            - "activities/M01-02-Activity-GitHub.qmd"
        - section: "M02"
          contents:
          - "activities/M02-01-Activity-Hello-World.qmd"
          - "activities/M02-02-Activity-JupyterLab-on-Rivanna.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true