project:
  title: "{{< var site_title >}}"
  output-dir: docs
  type: website

website:
  title: "DS 5100 Activities"
  sidebar:
    style: "docked"
    search: true
    contents:
        - section: "M01"
          contents:
            - "activities/M01-01-Using-Rivanna.qmd"
            - "activities/M01-02-Activity-GitHub.qmd"
        - section: "M02"
          contents:
          - "activities/M02-01-Activity-Hello-World.qmd"
          - "activities/M02-02-Activity-JupyterLab-on-Rivanna.qmd"

# - href: activities/M01-01-Using-Rivanna.qmd
#   text: "Activity 1: Using Rivanna"
# - href: activities/M01-02-Activity-GitHub.qmd
#   text: "Activity 2: Git and GitHub"
# - href: activities/M02-01-Activity-Hello-World.qmd
#   text: "Activity 1: Hello, World!"
# - href: activities/M02-02-Activity-JupyterLab-on-Rivanna.qmd
#   text: "Activity 2: Jupyter Lab on Rivanna"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true